steps:
  #Execute SonarCloud Scan
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['verify', 'sonar:sonar','-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=sushil-sonar-organization','-Dsonar.projectKey=sushil-sonar-project','-Dsonar.login=${_SONAR_TOKEN}']
  - name: 'ubuntu'
    entrypoint: bash
    args: 
        - '-c'
        - |-
          apt-get update
          apt-get -y install maven 
          SNYK_TOKEN=${_SNYK_TOKEN}
          export SNYK_TOKEN
          mvn snyk:test -fn 
    id: SCA Scan using Snyk in GCP DevSecOps Pipeline  